/home/aih/fatih.oezluegedik/.bashrc: line 803: warning: here-document at line 255 delimited by end-of-file (wanted `EOF')
/home/aih/fatih.oezluegedik/.bashrc: line 255: EOFcat: command not found
/home/aih/fatih.oezluegedik/miniconda3/envs/caitomorph/lib/python3.10/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
  0%|          | 0/1307 [00:00<?, ?it/s]  0%|          | 0/1307 [00:13<?, ?it/s]
Traceback (most recent call last):
  File "/ictstr01/groups/labs/marr/qscd01/workspace/fatih.oezluegedik/mixture_of_aggregators/train_5fold_test_fixed.py", line 268, in <module>
    main()
  File "/ictstr01/groups/labs/marr/qscd01/workspace/fatih.oezluegedik/mixture_of_aggregators/train_5fold_test_fixed.py", line 237, in main
    model, conf_matrix = train_obj.launch_training()
  File "/ictstr01/groups/labs/marr/qscd01/workspace/fatih.oezluegedik/mixture_of_aggregators/model_train.py", line 61, in launch_training
    val_metrics = self._run_epoch(ep, backprop_every=self.grad_accum)
  File "/ictstr01/groups/labs/marr/qscd01/workspace/fatih.oezluegedik/mixture_of_aggregators/model_train.py", line 119, in _run_epoch
    loss_out = loss_func(prediction, label)
  File "/home/aih/fatih.oezluegedik/miniconda3/envs/caitomorph/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/aih/fatih.oezluegedik/miniconda3/envs/caitomorph/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aih/fatih.oezluegedik/miniconda3/envs/caitomorph/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 1297, in forward
    return F.cross_entropy(
  File "/home/aih/fatih.oezluegedik/miniconda3/envs/caitomorph/lib/python3.10/site-packages/torch/nn/functional.py", line 3494, in cross_entropy
    return torch._C._nn.cross_entropy_loss(
RuntimeError: Expected target size [1, 8], got [1]
