/home/aih/fatih.oezluegedik/.bashrc: line 803: warning: here-document at line 255 delimited by end-of-file (wanted `EOF')
/home/aih/fatih.oezluegedik/.bashrc: line 255: EOFcat: command not found
/home/aih/fatih.oezluegedik/miniconda3/envs/caitomorph/lib/python3.10/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
